### ISSUE TITLE
missing: square root?

### ISSUE THREAD

**Issue by seanw2020** [jgperrin/net.jgp.books.spark.ch05#5]
First, thank you for the book! It's so great!

Second, and maybe I'm misunderstanding, but aren't we trying to take the square root below, not just their addition? As written, it seems closer to variance.
 https://github.com/jgperrin/net.jgp.books.spark.ch05/blob/0f1f65642a34c27ddb756cbda2552d82bc43c4c5/src/main/java/net/jgp/books/spark/ch05/lab100_pi_compute/PiComputeApp.java#L40

Shouldn't it be this?

> return (sqrt(x * x + y * y) <= 1) ? 1 : 0;

After importing java.lang.Math, that change compiles but it doesn't seem to get the answer any closer to or further away from 3.14159..., but maybe it's the randomly created data set...

**Comment by seanw2020** [comment]
Sorry, false alarm. I hadn't yet turned the page :-)

>WHY DIDN’T I RETURN A SQUARE ROOT? Take a look at the return value of the call() method in the mapper. If you follow the Pythagorean theorem, you would need to return the square root of the sum of the squares of x and y. However, as those values are under 1, it does not matter: the dart is in the circle (or not), and we do not care about the exact distance from the origin to the throw, just that it’s the square. Therefore, we can spare the expensive square root operation.

**Comment by jgperrin** [comment]
Hey Sean, thanks for the nice words on the book :) - feel free to share them on Amazon, even if you did not get the book there. 

Yeah, I had this question a lot by the reviewers, then I added the comment in the book :). As you experimented (and this is exactly how I'd hope people would use the labs, so thank you!) you demonstrated my theory! Thanks! 

Enjoy the rest of the book.
